apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-application
  labels:
    app: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container-app
        image: docksaita/container-app
        ports:
        - containerPort: 80
---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: application-rollout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    blueGreen:
      activeService: app-service
      previewService: app-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container-newapp
        image: docksaita/container-app
        ports:
        - containerPort: 80


---
# Nodeport service to expose the application
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
